version: "3.7"
services:
  mysql:
    image: mysql:8
    ports:
      - 3310:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
  adminer:
    image: adminer
    ports:
      - 8082:8080
#  mongodb:
#    image: mongo
#    container_name: mongodb
#    ports:
#      - 27017:27017
#  mongo-ui:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    depends_on:
#      - mongo